[prune]
   go-tests = true
   # we only prune test as other options will remove from aws-sdk-go 
   # what we nedd to run `make generate` on the project
   # see https://github.com/golang/dep/issues/1561

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.10.27"

[[constraint]]
  name = "github.com/boltdb/bolt"
  version = "1.3.1"

[[constraint]]
  branch = "master"
  name = "github.com/chzyer/readline"
 
[[constraint]]
  name = "github.com/fatih/color"
  version = "1.5.0"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.4.0"

[[constraint]]
  branch = "master"
  name = "github.com/mitchellh/ioprogress"

[[constraint]]
  name = "github.com/oklog/ulid"
  version = "0.3.0"

[[constraint]]
  branch = "master"
  name = "github.com/olekukonko/tablewriter"

[[constraint]]
  branch = "master"
  name = "github.com/spf13/cobra"

[[constraint]]
  name = "github.com/wallix/awless-scheduler"
  version = "0.0.6"

[[constraint]]
  branch = "master"
  name = "github.com/wallix/triplestore"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[[constraint]]
  name = "gopkg.in/src-d/go-git.v4"
  version = "=4.0.0-rc13"

[[constraint]]
  branch = "master"
  name = "github.com/boombuler/barcode"